version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
  # https://caddyserver.com/docs/running#docker-compose
  caddy:
    image: caddy:<version>
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
  postgres:
    image: docker.io/library/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: projektwahl
    volumes:
      #      - db-data:/var/lib/postgresql
      - ./src/server/setup.sql:/opt/projektwahl-lit/src/server/setup.sql
      - ./setup-postgresql.sh:/docker-entrypoint-initdb.d/setup-postgresql.sh
volumes:
  db-data:
  caddy_data:
  caddy_config: