version: "3.8"
services:
  backend:
    image: docker.io/library/node:21
    stop_grace_period: 1s
    command: npm run server
    working_dir: /app
    ports:
      - "8443:8443"
    volumes:
      - .:/app
    environment:
      PORT: "8443"
      DATABASE_URL: postgres://projektwahl@postgres/projektwahl
      BASE_URL: https://localhost
      CREDENTIALS_DIRECTORY: /app
  # https://caddyserver.com/docs/running#docker-compose
  caddy:
    image: docker.io/library/caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
      - caddy_data:/data
      - caddy_config:/config
  postgres:
    image: docker.io/library/postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: projektwahl
    volumes:
      - projektwahl-postgres:/var/lib/postgresql/data
volumes:
  projektwahl-postgres:
  caddy_data:
  caddy_config: