version: "3.8"
# https://docs.docker.com/compose/compose-file/
# sudo docker compose up --build
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    networks:
      - front-tier
      - back-tier
    healthcheck:
      # TODO FIXME test an API endpoint so that this is tested fully
      test: "curl --fail --insecure -X POST -H 'x-csrf-protection: projektwahl' -d {} https://localhost:8443/api/v1/login"
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 0s
    # https://docs.docker.com/compose/startup-order/
  #    configs:
  #      - httpd-config

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8443:443"
    networks:
      - front-tier
    volumes:
      - ./docs/sites-enabled-projektwahl.conf:/etc/nginx/conf.d/default.conf
    #    secrets:
    #      - server-certificate
    #      - server-key
    healthcheck:
      # TODO FIXME test an API endpoint so that this is tested fully
      test: "curl --fail --insecure https://localhost:443"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s

  postgres:
    image: docker.io/library/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: projektwahl
    volumes:
      #      - db-data:/var/lib/postgresql
      - ./src/server/setup.sql:/opt/projektwahl-lit/src/server/setup.sql
      - ./setup-postgresql.sh:/docker-entrypoint-initdb.d/setup-postgresql.sh
    networks:
      - back-tier

volumes:
  db-data:

#configs:
#  httpd-config:
#    external: true

#secrets:
#  server-certificate:
#    file: /opt/projektwahl-lit/cert.pem
#  server-key:
#    file: /opt/projektwahl-lit/key.pem

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
