# https://docs.docker.com/compose/compose-file/
# sudo docker compose up
services:
  frontend:
    image: projektwahl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - front-tier
      - back-tier
#    configs:
#      - httpd-config
#    secrets:
#      - server-certificate

  backend:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: projektwahl
      POSTGRES_DB: projektwahl
      POSTGRES_PASSWORD: projektwahl
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - back-tier

volumes:
  db-data:

#configs:
#  httpd-config:
#    external: true

#secrets:
#  server-certificate:
#    external: true

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
