version: "3.8"
services:
  # https://caddyserver.com/docs/running#docker-compose
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
  postgres:
    image: docker.io/library/postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: projektwahl
    volumes:
      - projektwahl-postgres:/var/lib/postgresql/data
volumes:
  projektwahl-postgres:
  caddy_data:
  caddy_config: