# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 Moritz Hedtke <Moritz.Hedtke@t-online.de>
# https://docs.docker.com/engine/reference/builder/
# docker build -f Dockerfile-reverse-proxy -t projektwahl-reverse-proxy .

# TODO https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

FROM nginx
COPY --from=projektwahl /opt/projektwahl-lit /opt/projektwahl-lit
RUN openssl req -x509 -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' -keyout key.pem -out cert.pem
