# https://docs.docker.com/compose/compose-file/
# sudo docker compose up
services:
  frontend:
    image: projektwahl
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - front-tier
      - back-tier
#    configs:
#      - httpd-config

  reverse-proxy:
    image: nginx
    ports:
    - "8443:443"
    networks:
      - front-tier
    volumes:
      - ./docs/sites-enabled-projektwahl.conf:/etc/nginx/conf.d/default.conf
    secrets:
      - server-certificate
      - server-key

  backend:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: projektwahl
      POSTGRES_DB: projektwahl
      POSTGRES_PASSWORD: projektwahl
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - back-tier

volumes:
  db-data:

#configs:
#  httpd-config:
#    external: true

secrets:
  server-certificate:
    file: /opt/projektwahl-lit/cert.pem
  server-key:
    file: /opt/projektwahl-lit/key.pem

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
