#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 Moritz Hedtke <Moritz.Hedtke@t-online.de>
. "$(dirname "$0")/_/husky.sh"

reuse lint
npm run format
npm run check
npm run lint
