# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 Moritz Hedtke <Moritz.Hedtke@t-online.de>
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # 17.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: ls -R /opt/hostedtoolcache/node/
      - run: cp dangerous-package.json package.json
      - run: npm install
      - run: npm run format:check
      - run: ./node_modules/@dev.mohe/argon2/build.sh /opt/hostedtoolcache/node/$(node -v | cut -c2-)/x64/include/node
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run localize-extract
      - run: git checkout -- package.json package-lock.json
      - run: git update-index --refresh
      - run: git diff-index --quiet HEAD --
