name: Deployment

concurrency: staging

on:
  push:
    branches:
      - deploy

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: SSH
        run: ssh moritz@staging.projektwahl.selfmade4u.de echo test
