name: Deployment

concurrency: staging

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: SSH
        run: |
          ssh moritz@staging.projektwahl.selfmade4u.de << EOF
          cd /opt/projektwahl-lit
          git worktree add ../projektwahl-lits/main origin/main
          cd ../projektwahl-lits/main
          git pull origin main
          npm install
          npx node-pre-gyp rebuild -C ./node_modules/argon2
          npm run localize-build
          npm run build
          npm run purgecss
          sudo /usr/bin/systemctl enable --now projektwahl@main.socket
          EOF
