name: Deployment

concurrency: staging

on:
  push:
    branches:
      - deploy

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: ssh -i <(echo $SSH_PRIVATE_KEY) moritz@staging.projektwahl.selfmade4u.de echo test
