name: Deployment

concurrency: staging

on:
  push:
    branches:
      - main
      - mohe2015-patch-1
      - staging

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: SSH
        run: |
          set -x
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo $GIT_BRANCH
          ssh moritz@staging.projektwahl.selfmade4u.de << EOF
          set -x
          cd /opt/projektwahl-lit
          git fetch origin
          git worktree add ../projektwahl-lits/$GIT_BRANCH origin/$GIT_BRANCH
          cd /opt/projektwahl-lits/$GIT_BRANCH
          git pull origin $GIT_BRANCH
          PORT=\$(cat /opt/projektwahl-lits/$GIT_BRANCH/.github/port)
          echo \$PORT
          npm install
          npx node-pre-gyp rebuild -C ./node_modules/argon2
          npm run localize-build
          npm run build
          npm run purgecss
          sudo /usr/bin/systemctl enable --now projektwahl@\$PORT.socket
          EOF
