enableScripts: false
plugins:
  - ../../packages/yarn-plugin-dependencies-from-source/bundles/@yarnpkg/plugin-dependencies-from-source.js
yarnPath: ../../.yarn/releases/yarn-3.1.0.cjs
defaultProtocol: "custom:"